[package]
name = "nostr-sdk-ffi"
version = "0.1.0"
edition = "2021"
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
keywords = ["nostr", "sdk", "rust", "ffi"]

[lib]
name = "nostrsdk"
crate-type = ["cdylib", "staticlib"]

[dependencies]
log = "0.4"
nostr  = { path = "../../crates/nostr" }
nostr-ffi  = { path = "../nostr-ffi" }
nostr-sdk  = { path = "../../crates/nostr-sdk", default-features = false, features = ["all-nips", "blocking"] }
parking_lot = "0.12.1"
uniffi = { git = "https://github.com/mozilla/uniffi-rs", rev = "b50a66fb95ca1f9cf69b25e020f7c3382c0ce528" }
uniffi_macros = { git = "https://github.com/mozilla/uniffi-rs", rev = "b50a66fb95ca1f9cf69b25e020f7c3382c0ce528" }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13"

[build-dependencies]
uniffi_build = { git = "https://github.com/mozilla/uniffi-rs", rev = "b50a66fb95ca1f9cf69b25e020f7c3382c0ce528", features = ["builtin-bindgen"] }
